version: "3.9"

services:
  api:
    restart: always
    build:
      context: .
      dockerfile: ./docker/api/local/express/Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - mongodb
      - redis
    # ports:
    #   - "1997:1997"
    env_file:
      - ./apps/api/.env
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - invoice

  web:
    build:
      context: .
      dockerfile: ./docker/web/local/nextjs/Dockerfile
    restart: on-failure
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - invoice

  mongodb:
    image: mongo:7.0.9-jammy
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    networks:
      - invoice

  mongo-express:
    image: mongo-express:1.0-18
    depends_on:
      - mongodb
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123456
    networks:
      - invoice

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - invoice

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - invoice

  nginx:
    build:
      context: ./docker/api/local/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - api
    volumes:
      - static_volume:/app/staticfiles
      - pdf_volume:/app/docs

    networks:
      - invoice

networks:
  invoice:
    driver: bridge

volumes:
  mongodb-data:
  redis-data:
  static_volume:
  pdf_volume:
